#:schema node_modules/wrangler/config-schema.json
name = "ai-img"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[[r2_buckets]]
bucket_name = "ai-img"
binding = "BUCKET"

[vars]
CLOUDFLARE_ACCOUNT_ID = "5445f664fc2c76e9f50b40ab589e8bd9"
